security:
    providers:
        in_memory:
            memory:
                users:
                    test:
                        password: test
    encoders:
        Symfony\Component\Security\Core\User\User: plaintext
    firewalls:
        login:
            pattern:  ^/auth/login
            stateless: true
            anonymous: true
            provider: in_memory
            json_login:
                check_path: /auth/login
                success_handler: lexik_jwt_authentication.handler.authentication_success
                failure_handler: lexik_jwt_authentication.handler.authentication_failure
                username_path: login
                password_path: password
        api:
            pattern:   ^/
            stateless: true
            provider: in_memory
            guard:
                authenticators:
                    - lexik_jwt_authentication.jwt_token_authenticator
    access_control:
        - { path: ^/auth/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/, roles: IS_AUTHENTICATED_FULLY }
